export const SET_LOGIN = "SET_LOGIN";
export const SET_LOCATION = "SET_LOCATION";
export const SET_VIEW_COUNT = "SET_VIEW_COUNT";
export const SET_TOTAL_VIEW_COUNT = "SET_TOTAL_VIEW_COUNT";
export const SET_VIEW_STATIC = "SET_VIEW_STATIC";
export const SET_VIEW_STATIC_LIMIT = "SET_VIEW_STATIC_LIMIT";
export const SET_TOKEN = "SET_TOKEN";